add skip params for findMany method
themetalfleece/neogma pull request #8
Opened 2021-03-09 12:50 UTC by tears330

- Add skip param for findMany method to resolve pagination logic
```ts
  Apps.findMany({
    where: {
      platform: where.platform
    },
    limit: pageSize,
    skip: pageNo * pageSize
  });
```

2021-03-19 07:01 UTC, themetalfleece requested changes
Thanks a lot for your contribution! Also, sorry for the late reply.
These are indeed useful parameters.
I think that I have noticed a bug which could be detected by a change in the unit testing (I've added both as comments). Let me know what you think, and I'd be happy to commit those changes if you want me to.

2021-03-19 07:01 UTC, themetalfleece commented on src/Queries/Where/Where.ts
> +                        value: value[Op.in],
I suppose this value should be `value[Op.contains]`

2021-03-19 07:01 UTC, themetalfleece commented on src/Queries/Where/Where.spec.ts
> +            ).toBeTruthy();
I would also expect the bind param value of `d` to be `test-string`, like:
`expect(where.getBindParam().get().d).toEqual('test-string');`

2021-03-19 07:39 UTC, tears330 commented
Sorry for missing logic which about how to bind params , just fix that.
I just use neogma in my project , and implements some useful method for the neogma instance (like `findAndCount`).
If u interested about that , i will take another PR about that 🙈

2021-03-19 08:58 UTC, themetalfleece approved these changes

2021-03-19 09:05 UTC, themetalfleece commented
Glad to hear that you're using neogma in your project!
Sure, feel free to submit PRs with whatever you think would be useful! I am mostly using the create/edit/delete Model operations, and using `QueryBuilder` for finds. But of course, all these improvements for the find Model operations are very useful.

2021-03-19 09:06 UTC, merged

2021-04-07 17:58 UTC, themetalfleece commented
Published in `1.7.0`, docs added.